import textwrap
import re

def _parse_model_summary(summary_text: str) -> str:
    """
    Parses the raw TensorFlow model summary text to extract layer rows 
    for a structured HTML table. It ignores the header and footer lines,
    focusing only on lines containing layer data (which start with '│').
    """
    summary_rows = []
    
    # Iterate through the summary line by line
    for line in summary_text.split('\n'):
        
        # Identify lines containing layer data (these lines start with the vertical bar character)
        if line.startswith('│') and len(line.split('│')) >= 4:
            # The split will look something like ['', ' input_1 (Dense) ', ' (None, 32) ', ' 480 ', '']
            parts = [p.strip() for p in line.split('│') if p.strip()]
            
            if len(parts) == 3:
                layer_type = parts[0]
                output_shape = parts[1]
                param_count = parts[2]
                
                # Generate HTML row using Tailwind classes
                row = f"""
        <tr class="border-b border-gray-200">
            <td class="p-2 border border-gray-300 text-sm font-semibold text-gray-800">{layer_type}</td>
            <td class="p-2 border border-gray-300 text-sm font-mono text-gray-700">{output_shape}</td>
            <td class="p-2 border border-gray-300 text-sm font-mono text-gray-700 text-right">{param_count}</td>
        </tr>
                """
                summary_rows.append(row.strip())
    
    return "\n".join(summary_rows)


def generate_html_report(results: dict, target_col: str, batch_size: int) -> str:
    """
    Generates the full HTML report based on analysis results.

    This function dynamically creates two tables (Training Log and Model Summary) 
    and incorporates all metrics and configuration details into a single, styled 
    HTML report using Tailwind CSS classes.

    Args:
        results (dict): Dictionary containing model metrics, logs, and config data 
                        generated by the main pipeline.
        target_col (str): The name of the target column being predicted (e.g., 'trip_duration').
        batch_size (int): The batch size used during model training.
        
    Returns:
        str: The complete HTML content of the report.
    """

    # --- 1. Generate Training Log Table HTML ---
    log_rows = ""
    for log in results['training_log']:
        log_rows += f"""
        <tr class="hover:bg-gray-50 transition">
            <td class="p-2 border border-gray-200 text-center font-mono text-xs text-gray-700">{log['epoch']}</td>
            <td class="p-2 border border-gray-200 text-right font-mono text-sm text-gray-800">{log['loss']}</td>
            <td class="p-2 border border-gray-200 text-right font-mono text-sm text-gray-800">{log['mae']}</td>
            <td class="p-2 border border-gray-200 text-right font-mono text-sm text-gray-800 bg-blue-50">{log['val_loss']}</td>
            <td class="p-2 border border-gray-200 text-right font-mono text-sm text-gray-800 bg-blue-50">{log['val_mae']}</td>
        </tr>
        """
    
    # --- 2. Generate Model Summary Table HTML by parsing the raw summary ---
    # Parse the raw summary text to get clean HTML table rows
    summary_rows = _parse_model_summary(results['model_summary'])
    
    # Use the structured HTML table for the Model Summary section
    model_summary_html = f"""
    <div class="overflow-x-auto mb-4 shadow-md rounded-lg">
        <table class="min-w-full bg-white">
            <thead>
                <tr class="bg-gray-100 text-left text-xs font-semibold uppercase tracking-wider text-gray-600">
                    <th class="p-2 border border-gray-300">Layer (type)</th>
                    <th class="p-2 border border-gray-300">Output Shape</th>
                    <th class="p-2 border border-gray-300 text-right">Param #</th>
                </tr>
            </thead>
            <tbody>
                {summary_rows}
            </tbody>
        </table>
    </div>
    <div class="text-sm font-semibold text-gray-700 space-y-1 p-3 bg-gray-50 rounded-lg">
        <p>Total params: {results['total_params']}</p>
        <p>Trainable params: <span class="text-green-600">{results['trainable_params']}</span></p>
        <p>Non-trainable params: {results['non_trainable_params']}</p>
    </div>
    """


    # --- 3. Compile Full HTML Content ---
    
    # Format R2 score for percentage display
    r2_percentage = f"{(float(results['r2']) * 100):.2f}%"

    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NN Regression Performance Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=IBM+Plex+Mono:wght@400&display=swap');
        body {{ font-family: 'Inter', sans-serif; background-color: #f7f9fc; }}
        .card {{ box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1); }}
        .font-mono {{ font-family: 'IBM Plex Mono', monospace; }}
    </style>
</head>
<body class="p-4 sm:p-8">

    <div class="max-w-5xl mx-auto bg-white p-6 md:p-10 rounded-xl card">
        <h1 class="text-3xl font-bold text-gray-800 border-b-4 border-indigo-500 pb-2 mb-6">
            Neural Network Regression Performance Report: {results['model_name']}
        </h1>
        <p class="text-gray-600 mb-8">
            Detailed summary of the model training, convergence, and evaluation process for the <code>{target_col}</code> prediction task.
        </p>

        <!-- METRICS SECTION -->
        <div class="mb-8">
            <h2 class="text-2xl font-semibold text-indigo-700 mb-4 border-b pb-1">1. Evaluation Metrics</h2>
            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">

                <!-- MAE CARD -->
                <div class="p-5 bg-white border border-gray-200 rounded-xl shadow-lg hover:shadow-xl transition duration-300">
                    <p class="text-sm font-medium text-gray-500">Mean Absolute Error (MAE)</p>
                    <p class="text-3xl font-bold text-red-600 font-mono">{results['mae']}</p>
                    <p class="text-xs text-gray-500">Avg. error in seconds</p>
                </div>

                <!-- RMSE CARD -->
                <div class="p-5 bg-white border border-gray-200 rounded-xl shadow-lg hover:shadow-xl transition duration-300">
                    <p class="text-sm font-medium text-gray-500">Root Mean Squared Error (RMSE)</p>
                    <p class="text-3xl font-bold text-red-700 font-mono">{results['rmse']}</p>
                    <p class="text-xs text-gray-500">Scaled error metric</p>
                </div>

                <!-- R2 CARD -->
                <div class="p-5 bg-white border border-gray-200 rounded-xl shadow-lg hover:shadow-xl transition duration-300">
                    <p class="text-sm font-medium text-gray-500">Coefficient of Determination ($R^2$)</p>
                    <p class="text-3xl font-bold text-green-600 font-mono">{r2_percentage}</p>
                    <p class="text-xs text-gray-500">Variance explained</p>
                </div>

                <!-- MSE CARD -->
                <div class="p-5 bg-white border border-gray-200 rounded-xl shadow-lg hover:shadow-xl transition duration-300">
                    <p class="text-sm font-medium text-gray-500">Mean Squared Error (MSE)</p>
                    <p class="text-3xl font-bold text-red-500 font-mono">{results['mse']}</p>
                    <p class="text-xs text-gray-500">Penalty for large errors</p>
                </div>
            </div>
        </div>

        <!-- TRAINING LOG SECTION -->
        <div class="mb-8">
            <h2 class="text-2xl font-semibold text-indigo-700 mb-4 border-b pb-1">2. Training Convergence Log ({len(results['training_log'])} Epochs)</h2>
            <div class="overflow-x-auto rounded-lg border border-gray-200">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th class="p-2 border border-gray-200 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Epoch</th>
                            <th class="p-2 border border-gray-200 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Loss (Train)</th>
                            <th class="p-2 border border-gray-200 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">MAE (Train)</th>
                            <th class="p-2 border border-gray-200 text-right text-xs font-medium text-blue-700 uppercase tracking-wider bg-blue-100">Loss (Validation)</th>
                            <th class="p-2 border border-gray-200 text-right text-xs font-medium text-blue-700 uppercase tracking-wider bg-blue-100">MAE (Validation)</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        {log_rows}
                    </tbody>
                </table>
            </div>
        </div>

        <!-- MODEL SUMMARY SECTION -->
        <div class="mb-8">
            <h2 class="text-2xl font-semibold text-indigo-700 mb-4 border-b pb-1">3. Model Architecture Summary</h2>
            {model_summary_html}
        </div>


        <!-- CONFIGURATION SECTION -->
        <div class="mb-8 pt-4 border-t border-gray-200">
            <h2 class="text-2xl font-semibold text-indigo-700 mb-4 border-b pb-1">4. Environment and Training Configuration</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                <div class="bg-gray-50 p-3 rounded-lg"><span class="font-semibold text-gray-700">Total Samples:</span> {results['data_shape']}</div>
                <div class="bg-gray-50 p-3 rounded-lg"><span class="font-semibold text-gray-700">Input Features (after preprocessing):</span> {results['input_features']}</div>
                <div class="bg-gray-50 p-3 rounded-lg"><span class="font-semibold text-gray-700">Model Name:</span> <code>{results['model_name']}</code></div>
                <div class="bg-gray-50 p-3 rounded-lg"><span class="font-semibold text-gray-700">Batch Size:</span> {batch_size}</div>
                <div class="bg-gray-50 p-3 rounded-lg md:col-span-2"><span class="font-semibold text-gray-700">Training Duration:</span> <span class="font-bold text-green-600">{results['training_time']}</span></div>
                <div class="bg-yellow-50 p-3 rounded-lg md:col-span-2"><span class="font-semibold text-gray-700">Hardware:</span> <span class="text-yellow-800">{results['hardware']}</span></div>
                <div class="bg-indigo-50 p-3 rounded-lg md:col-span-2"><span class="font-semibold text-gray-700">Target Column:</span> <code>{target_col}</code></div>
                <div class="bg-gray-50 p-3 rounded-lg md:col-span-2"><span class="font-semibold text-gray-700">Numerical Features:</span> {results['numerical_features']}</div>
                <div class="bg-gray-50 p-3 rounded-lg md:col-span-2"><span class="font-semibold text-gray-700">Categorical Features:</span> {results['categorical_features']}</div>
            </div>
        </div>

    </div>

</body>
</html>
    """
    return textwrap.dedent(html_content)
